name: Update arXiv Paper Feed

on:
  schedule:
    # Run at midnight UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  fetch-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch latest papers from arXiv
        run: python arxiv_feed/fetch_papers.py

      - name: Commit and push updated papers.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add arxiv_feed/papers.json arxiv_feed/papers.js
          if git diff --cached --quiet; then
            echo "No changes to papers.json — skipping commit."
          else
            git commit -m "chore: update arXiv paper feed [$(date -u +'%Y-%m-%d')]"
            git push
          fi
